
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Salsabila Putri Ray
 */
public class transaksi extends javax.swing.JFrame {

    /**
     * Creates new form transaksi
     */
    String maem ="";
    int harga;
 
    public transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        kasir = new javax.swing.JTextField();
        meja = new javax.swing.JTextField();
        soto = new javax.swing.JButton();
        rawon = new javax.swing.JButton();
        mie = new javax.swing.JButton();
        nasgor = new javax.swing.JButton();
        esteh = new javax.swing.JButton();
        esje = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tehpa = new javax.swing.JButton();
        kosu = new javax.swing.JButton();
        waktu = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESTORANKU");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(330, 10, 400, 71);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 19, 1050, 90));

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 100, 40));

        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 100, 40));

        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 100, 40));

        jButton4.setText("print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 100, 40));
        jPanel1.add(kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 50));
        jPanel1.add(meja, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 150, 50));

        soto.setText("Soto Ayam");
        soto.setToolTipText("");
        soto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotoActionPerformed(evt);
            }
        });
        jPanel1.add(soto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, 40));

        rawon.setText("Rawon");
        rawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawonActionPerformed(evt);
            }
        });
        jPanel1.add(rawon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 40));

        mie.setText("Mie Rebus");
        mie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mieActionPerformed(evt);
            }
        });
        jPanel1.add(mie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 110, 40));

        nasgor.setText("Nasi Goreng");
        nasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasgorActionPerformed(evt);
            }
        });
        jPanel1.add(nasgor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 120, 40));

        esteh.setText("Es Teh");
        esteh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estehActionPerformed(evt);
            }
        });
        jPanel1.add(esteh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        esje.setText("Es Jeruk");
        esje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esjeActionPerformed(evt);
            }
        });
        jPanel1.add(esje, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 101, -1));

        jLabel2.setText("Kasir");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setText("No. Meja");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 70, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "meja", "kasir", "waktu", "hasil", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 580, 540));

        tehpa.setText("Teh Panas");
        tehpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tehpaActionPerformed(evt);
            }
        });
        jPanel1.add(tehpa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 110, -1));

        kosu.setText("Kopi Susu");
        kosu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kosuActionPerformed(evt);
            }
        });
        jPanel1.add(kosu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));
        jPanel1.add(waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 200, 40));

        jLabel6.setText("Waktu");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 200, 50));

        jLabel7.setText("Total");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jLabel8.setFont(new java.awt.Font("NewsGoth Cn BT", 0, 24)); // NOI18N
        jLabel8.setText("<html>\nSoto Ayam 8000\n<br>\nMie Rebus 5000\n<br> \nRawon 9000\n<br> \nNasi Gooreng 8000\n<br> \nKopi Susu 3000\n<br> \nTeh panas 2000\n<br> \nEs Teh 2500\n<br> \nEs Jeruk 2500 \n</html>\n\n");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 160, 250));
        jPanel1.add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, 220, 220));

        jButton5.setText("refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1087, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 1109, 821);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(waktu.getDate());
        if("".equals(meja.getText()) || "".equals(kasir.getText()) || tanggal.equals("") || "".equals(hasil.getText()) || "".equals(total.getText())){
        JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else{
           
            String SQL = "INSERT INTO tb_transaksi (meja,kasir,waktu,hasil,total)" +"VALUES('"+meja.getText()+"','"+kasir.getText()+"','"+tanggal+"','"+hasil.getText()+"','"+total.getText()+"')";
            int status = koneksinya.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else{
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasgorActionPerformed
        // TODO add your handling code here:
        maem+="Nasi Goreng \n";
        hasil.setText(maem);
        
    }//GEN-LAST:event_nasgorActionPerformed

    private void rawonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawonActionPerformed
        // TODO add your handling code here:
        maem+="Rawon \n";
        hasil.setText(maem);
    }//GEN-LAST:event_rawonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
         kasir.setText("");
        meja.setText("");
        total.setText(""); 
        hasil.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        if (baris != -1){
            String meja = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE meja='"+meja+"'";
            int status = koneksinya.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
            
        } else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       MessageFormat header = new MessageFormat("Laporan Transaksi");
       MessageFormat footer = new MessageFormat("Page {0,number,integer}    ");
       try{
           tabel.print(JTable.PrintMode.FIT_WIDTH, header,footer, true, null, true, null);
      
       } catch(java.awt.print.PrinterException e){
           System.err.format("Cannot Print %s%n", e.getMessage());
       }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sotoActionPerformed
        // TODO add your handling code here:
        maem+="Soto Ayam \n";
        hasil.setText(maem);
    }//GEN-LAST:event_sotoActionPerformed

    private void mieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mieActionPerformed
        // TODO add your handling code here:
        maem+="Mie Ayam \n";
        hasil.setText(maem);
    }//GEN-LAST:event_mieActionPerformed

    private void kosuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kosuActionPerformed
        // TODO add your handling code here:
        maem+="Kopi Susu \n";
        hasil.setText(maem);
    }//GEN-LAST:event_kosuActionPerformed

    private void tehpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tehpaActionPerformed
        // TODO add your handling code here:
        maem+="Teh Panas \n";
        hasil.setText(maem);
       
    }//GEN-LAST:event_tehpaActionPerformed

    private void estehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estehActionPerformed
        // TODO add your handling code here:
        maem+="Es Teh \n";
        hasil.setText(maem);
    }//GEN-LAST:event_estehActionPerformed

    private void esjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esjeActionPerformed
        // TODO add your handling code here:
        maem+="Es Jeruk \n";
        hasil.setText(maem);
    }//GEN-LAST:event_esjeActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
int baris = tabel.getSelectedRow();
        if (baris != -1){
            meja.setText(tabel.getValueAt(baris, 0).toString());
            kasir.setText(tabel.getValueAt(baris, 1).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
            dateFormat = date.parse(tabel.getValueAt(baris, 2).toString());
            } catch (ParseException ex){
                Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
            waktu.setDate(dateFormat);
            hasil.setText(tabel.getValueAt(baris, 3).toString());
            total.setText(tabel.getValueAt(baris, 4).toString());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton esje;
    private javax.swing.JButton esteh;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kasir;
    private javax.swing.JButton kosu;
    private javax.swing.JTextField meja;
    private javax.swing.JButton mie;
    private javax.swing.JButton nasgor;
    private javax.swing.JButton rawon;
    private javax.swing.JButton soto;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tehpa;
    private javax.swing.JTextField total;
    private com.toedter.calendar.JDateChooser waktu;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
    String kolom[] ={"meja","kasir","waktu","hasil","total"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_transaksi";
        ResultSet rs = (ResultSet) koneksinya.executeQuery(SQL);
        try {
            while(rs.next()){
                String meja = rs.getString(1);
                String kasir = rs.getString(2);
                String waktu = rs.getString(3);
                String hasil = rs.getString(4);
                String total = rs.getString(5);
                String data[] = {meja,kasir,waktu,hasil,total};
                dtm.addRow(data);
            }
        }catch(SQLException ex){
            Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(dtm);
    }
}
